[package]
name = "openai-chat"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
opai = { path = "../../openai" }
futures-util = "0.3.30"
tokio = { version = "1.39.2", features = ["full"] }
serde_json = "1.0.128"
